# Generated by Django 4.1.13 on 2024-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Seed_RepDate', models.IntegerField()),
                ('Seed_Year', models.IntegerField()),
                ('Seeds_YearWeek', models.IntegerField()),
                ('Seed_Varity', models.CharField(max_length=50)),
                ('Seed_RDCSD', models.CharField(max_length=100)),
                ('Seed_Stock2Sale', models.CharField(max_length=50)),
                ('Seed_Season', models.IntegerField()),
                ('Seed_Crop_Year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
